In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# Principal package imports
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import scipy as sc

# Scikit-learn package imports
from sklearn import feature_extraction, model_selection
from sklearn.metrics import root_mean_squared_error, mean_squared_error, roc_auc_score

# PyBKT package imports
import random
old_randint = random.randint
random.randint = lambda a, b: old_randint(a, int(b))
from pyBKT.models import Model
random.randint = old_randint

In [4]:
gymitrainer_df = pd.read_csv("/home/mlbd-project/updated_data/gymitrainer.csv")
display(gymitrainer_df.head())

mapping_df = pd.read_csv("/home/mlbd-project/updated_data/mapping.csv")
display(mapping_df.head())

,Unnamed: 0,id,chat_profile,tag,message_count,startTime,endTime,content
0,0,8d8b7ed3-393a-4fff-a3de-3cd515399efa,NaN,NaN,0,1741330528,1741330535,"['Hallo! Ich bin Gymitrainer, dein Tutor für d..."
1,1,f27276e8-eca8-419e-8f13-1677aac6c5b8,NaN,NaN,0,1741330363,1741330368,"['Hallo! Ich bin Gymitrainer, dein Tutor für d..."
2,2,b870f1ce-6fd3-4353-96c3-7fb44c9add19,NaN,NaN,0,1741330310,1741330326,"['Hallo! Ich bin Gymitrainer, dein Tutor für d..."
3,3,873d766b-baf9-4c88-a27b-9f842df763d8,NaN,NaN,0,1741330270,1741330294,"['Hallo! Ich bin Gymitrainer, dein Mathe-Tutor..."
4,4,2c470a15-7dc4-4b83-be81-61501b325d0d,NaN,NaN,0,1741123788,1741123799,"['Hallo! Ich bin Gymitrainer, dein Mathe-Tutor..."

,Unnamed: 0,user_id,delta,confidence,id
0,0,282,1039460,0.20016,c40e9e5f-39fa-415d-b806-69846ea659b3
1,1,282,1038323,0.20016,78a59adc-96b4-44c7-aad6-f669c944794e
2,2,282,966940,0.20017,419631b2-5dbb-4b1d-b323-b3c758c4933d
3,3,282,966558,0.20017,c2b07040-8023-4c68-bf45-0f7ab0a33b38
4,4,282,965864,0.20017,9d9501ba-732d-49e5-b40c-ba261a0db18f

In [8]:
# read files
#gymitrainer_df = pd.read_csv("/home/mlbd_project/m4-gogymi/gymitrainer.csv")
#mapping_df = pd.read_csv("/home/mlbd_project/m4-gogymi/mapping.csv")

# Threshold
threshold = 0.5

# filtering
filtered_mapping = mapping_df[mapping_df['confidence'] >= threshold]

# Get only matching gymitrainer records (inner join)
matched_gymitrainer = pd.merge(
    gymitrainer_df,
    filtered_mapping[['id', 'user_id']],
    on='id',
    how='inner'  
)

# Sort by user_id
matched_gymitrainer = matched_gymitrainer.sort_values(by='user_id')
display(matched_gymitrainer.head())

,Unnamed: 0,id,chat_profile,tag,message_count,startTime,endTime,content,user_id
1630,4454,321dae4e-6d92-40be-b780-232cecf3b586,NaN,NaN,1,1730219336,1730219336,['wie soll ich das rechnen'],4
1629,4453,74677c94-340b-4017-9cba-5d38cd1bf581,Aufsatz,Aufsatz,3,1730219315,1730220391,"[""Hey! Ich bin Gymitrainer, dein Experte für G...",4
305,772,109cbf59-7ca4-49d7-9879-40d79e666557,Aufsatz,Aufsatz,2,1738769310,1738769622,"[""Hey! Ich bin Gymitrainer, dein Experte für G...",6
313,803,bf6c477d-578b-4234-9126-636c64fc09a4,NaN,NaN,3,1738678028,1738681716,"['Hallo! Ich bin Gymitrainer, dein Mathe-Tutor...",6
526,1443,6923b14e-55b3-4aee-8d9c-fd5305295cb2,NaN,NaN,1,1736181505,1736184444,"['Hallo! Ich bin Gymitrainer, dein Mathe-Tutor...",6

In [9]:
# Count the number of conversations for each user_id
usage_counts = matched_gymitrainer['user_id'].value_counts().reset_index()

# Edit column names
usage_counts.columns = ['user_id', 'usage_count']

# sort by user_id
usage_counts = usage_counts.sort_values(by='user_id')

display(usage_counts)

     user_id  usage_count
278        4            2
69         6            9
279        7            2
167        9            4
275       11            3
..       ...          ...
374     4088            2
265     4089            3
575     4090            1
104     4092            7
207     4095            4

[576 rows x 2 columns]